[releases."9.20"]
published = "2010-11-18"
archive_url = "https://www.7-zip.org/a/lzma920.tar.bz2"
archive_file = "lzma920.tar.bz2"
archive_format = "tar.bz2"
source_page = "https://www.7-zip.org/download.html"

[releases."16.04"]
published = "2016-10-04"
archive_url = "https://www.7-zip.org/a/lzma1604.7z"
archive_file = "lzma1604.7z"
archive_format = "7z"
source_page = "https://www.7-zip.org/download.html"

[releases."19.00"]
published = "2019-02-21"
archive_url = "https://www.7-zip.org/a/lzma1900.7z"
archive_file = "lzma1900.7z"
archive_format = "7z"
source_page = "https://www.7-zip.org/download.html"

[releases."23.01"]
published = "2023-06-20"
archive_url = "https://www.7-zip.org/a/lzma2301.7z"
archive_file = "lzma2301.7z"
archive_format = "7z"
source_page = "https://www.7-zip.org/sdk.html"

[releases."26.00"]
published = "2026-02-12"
archive_url = "https://www.7-zip.org/a/lzma2600.7z"
archive_file = "lzma2600.7z"
archive_format = "7z"
source_page = "https://www.7-zip.org/sdk.html"
